### ISSUE TITLE
git fat status: error when no files present

### ISSUE THREAD

**Issue by leoll2** [leoll2/git-fat#1]
When the repo is empty, running `git fat status` gives the following error:

```
leoll2:~/aaa > git fat status
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/usr/local/bin/git-fat", line 1160, in <module>
    run_command(**kwargs)
  File "/usr/local/bin/git-fat", line 1080, in run_command
    getattr(gitfat, fn)(**kwargs)
  File "/usr/local/bin/git-fat", line 855, in cmd_status
    referenced = self.referenced_objects(**refargs)
  File "/usr/local/bin/git-fat", line 579, in referenced_objects
    rev = self.revparse("HEAD")
  File "/usr/local/bin/git-fat", line 470, in revparse
    return touni(subprocess.check_output(["git", "rev-parse", revname]).strip())
  File "/home/leoll2/.pyenv/versions/3.7.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/leoll2/.pyenv/versions/3.7.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
```

**Comment by leoll2** [comment]
**TODO**
- [ ] identify the root cause
- [ ] fix the bug
- [ ] add a test
